### Health Check
GET http://localhost:5000/api/health

###

POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "raviteja",
    "email": "raviteja@example.com",
    "password": "Password123"
}


### Login

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email":"raviteja@example.com",
    "password":"Password123"
}


### Current User

GET http://localhost:5000/api/auth/me

###

### Logout

POST http://localhost:5000/api/auth/logout