### Health Check
GET http://localhost:5000/api/health

###

POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "raviteja",
    "email": "raviteja@example.com",
    "password": "Password123"
}